



# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.




#Solution 1: using head and tail of data frame

resultguy <- data.frame(i=c(1,2))
while (tail(resultguy[,"i"],n=1) + head(tail(resultguy[,"i"],n=2),n=1)<4000000) {
  i <- tail(resultguy[,"i"],n=1) + head(tail(resultguy[,"i"],n=2),n=1)
  resultguy <- rbind(resultguy, i)
}

#remove odd numbers
resultguy <- resultguy[resultguy$i%% 2==0,]
sum(resultguy)





#Solution 2: using nrow of data frame

resultguy <- data.frame(i=c(1,2))
while (resultguy[nrow(resultguy),] + resultguy[nrow(resultguy)-1,]<4000000) {
  i <- resultguy[nrow(resultguy),] + resultguy[nrow(resultguy)-1,]
  resultguy <- rbind(resultguy, i)
}

#remove odd numbers
resultguy <- resultguy[resultguy$i%% 2==0,]
sum(resultguy)




